"use client";
import React, { useState } from "react";
import { Button } from "../../components/ui/button";
import {
  Search,
  Filter,
  Heart,
  Eye,
  MapPin,
  Star,
  QrCode,
  Tag,
  Clock,
  TrendingUp,
  CheckCircle,
  AlertCircle,
  Bookmark,
  EyeOff,
  X,
  Calendar,
  DollarSign,
  User,
  Package,
} from "lucide-react";
import {
  isApprovedBuyerZipCode,
  getNeighborhoodName,
} from "../../lib/zipcodes";

// Updated mock data to match ConsignCrew listing schema with ZIP codes
const mockListings = [
  {
    // Auto-generated by ConsignCrew
    item_id: "cc_001_2025_01_15_001",
    seller_id: "user_123",
    created_at: "2025-01-15T10:30:00Z",
    status: "LISTED",
    qr_code_url:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=cc_001_2025_01_15_001",
    image_urls_staged: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop",
    ],
    gtin: "1234567890123",
    insights_query: "modern leather sofa furniture seating living room",
    price_range_low: 750,
    price_range_high: 1100,
    list_price: 899.99,
    reserve_price: 650.0,
    fee_pct: 8.5,

    // Provided by seller
    title: "Modern Leather Sofa",
    description:
      "Premium leather sofa in excellent condition. Perfect for living room or office. Features high-quality construction and comfortable seating. This sofa has been well-maintained and shows minimal signs of wear. The leather is supple and the cushions provide excellent support. Includes matching throw pillows.",
    category_id: "furniture_seating_sofas",
    condition: "EXCELLENT",
    image_urls_original: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop",
    ],
    serial_number: "SOFA-2024-001",
    model_number: "MLS-3S-2024",
    discount_schedule: "Turbo-30",
    zip_code: "77019",

    // Display fields
    seller_name: "FurniturePro",
    location: "River Oaks / Upper Kirby",
    rating: 4.8,
    reviews: 12,
    timeLeft: "2d 14h",
    isFavorite: false,
  },
  {
    // Auto-generated by ConsignCrew
    item_id: "cc_002_2025_01_14_002",
    seller_id: "user_456",
    created_at: "2025-01-14T14:20:00Z",
    status: "LISTED",
    qr_code_url:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=cc_002_2025_01_14_002",
    image_urls_staged: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop",
    ],
    gtin: "9876543210987",
    insights_query: "iphone 13 pro smartphone mobile electronics",
    price_range_low: 650,
    price_range_high: 850,
    list_price: 749.99,
    reserve_price: 550.0,
    fee_pct: 7.5,

    // Provided by seller
    title: "iPhone 13 Pro - 256GB",
    description:
      "iPhone 13 Pro in good condition. Includes original box and charger. Minor scratches on screen protector. The phone has been used for about 18 months and is in excellent working condition. Battery health is at 87% and all features work perfectly. No water damage or major repairs.",
    category_id: "electronics_mobile_phones",
    condition: "GOOD",
    image_urls_original: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop",
    ],
    serial_number: "DNQH2K3L4M5N",
    model_number: "A2483",
    discount_schedule: "Classic-60",
    zip_code: "77056",

    // Display fields
    seller_name: "TechTrader",
    location: "Galleria / Tanglewood",
    rating: 4.9,
    reviews: 8,
    timeLeft: "1d 8h",
    isFavorite: true,
  },
  {
    // Auto-generated by ConsignCrew
    item_id: "cc_003_2025_01_13_003",
    seller_id: "user_789",
    created_at: "2025-01-13T09:15:00Z",
    status: "LISTED",
    qr_code_url:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=cc_003_2025_01_13_003",
    image_urls_staged: [
      "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=400&h=300&fit=crop",
    ],
    gtin: null,
    insights_query: "vintage mid-century coffee table furniture",
    price_range_low: 400,
    price_range_high: 600,
    list_price: 450.0,
    reserve_price: 350.0,
    fee_pct: 9.0,

    // Provided by seller
    title: "Vintage Mid-Century Coffee Table",
    description:
      'Authentic mid-century modern coffee table. Solid wood construction with beautiful patina. Perfect condition. This is a genuine piece from the 1960s, not a reproduction. The wood has developed a beautiful natural patina over the years. Dimensions are 48" x 24" x 18" high. Perfect for any mid-century modern or contemporary home.',
    category_id: "furniture_tables_coffee_tables",
    condition: "EXCELLENT",
    image_urls_original: [
      "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=400&h=300&fit=crop",
    ],
    serial_number: null,
    model_number: null,
    discount_schedule: "Turbo-30",
    zip_code: "77007",

    // Display fields
    seller_name: "VintageVault",
    location: "The Heights (Washington Corridor)",
    rating: 4.7,
    reviews: 15,
    timeLeft: "3d 22h",
    isFavorite: false,
  },
  {
    // Auto-generated by ConsignCrew
    item_id: "cc_004_2025_01_12_004",
    seller_id: "user_101",
    created_at: "2025-01-12T16:45:00Z",
    status: "LISTED",
    qr_code_url:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=cc_004_2025_01_12_004",
    image_urls_staged: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
    ],
    gtin: "4567891234567",
    insights_query: "nike air jordan 1 retro high sneakers",
    price_range_low: 250,
    price_range_high: 350,
    list_price: 299.99,
    reserve_price: 200.0,
    fee_pct: 6.5,

    // Provided by seller
    title: "Nike Air Jordan 1 Retro High",
    description:
      "Brand new Nike Air Jordan 1 Retro High. Never worn, original box included. Limited edition colorway. This is the 2024 release in the classic Chicago colorway. Size 10.5 US. The shoes are completely unworn and come with all original packaging, including the special edition box and extra laces.",
    category_id: "sports_outdoors_footwear",
    condition: "NEW",
    image_urls_original: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
    ],
    serial_number: "AJ1-2024-001",
    model_number: "555088-105",
    discount_schedule: "Classic-60",
    zip_code: "77005",

    // Display fields
    seller_name: "SneakerHead",
    location: "West University Place",
    rating: 4.6,
    reviews: 23,
    timeLeft: "5h 30m",
    isFavorite: false,
  },
  {
    // Auto-generated by ConsignCrew
    item_id: "cc_005_2025_01_11_005",
    seller_id: "user_202",
    created_at: "2025-01-11T11:30:00Z",
    status: "LISTED",
    qr_code_url:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=cc_005_2025_01_11_005",
    image_urls_staged: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=300&fit=crop",
    ],
    gtin: "7891234567890",
    insights_query: "samsung 65 inch 4k smart tv electronics",
    price_range_low: 500,
    price_range_high: 700,
    list_price: 599.99,
    reserve_price: 450.0,
    fee_pct: 8.0,

    // Provided by seller
    title: 'Samsung 65" 4K Smart TV',
    description:
      "Samsung 65-inch 4K Smart TV in like-new condition. Includes remote and wall mount. Perfect picture quality. This TV was purchased in 2023 and has been used sparingly. The picture quality is exceptional with vibrant colors and deep blacks. Includes the original Samsung remote, wall mount bracket, and all original documentation. No dead pixels or screen issues.",
    category_id: "electronics_tvs_video",
    condition: "EXCELLENT",
    image_urls_original: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=300&fit=crop",
    ],
    serial_number: "SN65Q80TAFXZA",
    model_number: "QN65Q80TAFXZA",
    discount_schedule: "Turbo-30",
    zip_code: "77024",

    // Display fields
    seller_name: "ElectronicsPlus",
    location: "Memorial / Memorial Villages",
    rating: 4.8,
    reviews: 6,
    timeLeft: "1d 16h",
    isFavorite: true,
  },
  {
    // Auto-generated by ConsignCrew
    item_id: "cc_006_2025_01_10_006",
    seller_id: "user_303",
    created_at: "2025-01-10T13:45:00Z",
    status: "LISTED",
    qr_code_url:
      "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=cc_006_2025_01_10_006",
    image_urls_staged: [
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
    ],
    gtin: null,
    insights_query: "handcrafted ceramic vase set home decor",
    price_range_low: 80,
    price_range_high: 120,
    list_price: 89.99,
    reserve_price: 60.0,
    fee_pct: 8.5,

    // Provided by seller
    title: "Handcrafted Ceramic Vase Set",
    description:
      "Beautiful handcrafted ceramic vase set. Perfect for home decoration. Each piece is unique and hand-painted. This set includes 3 vases of varying sizes (small, medium, large) in complementary earth tones. Each vase is hand-thrown and hand-painted by local artisans. The glazes are food-safe and the pieces are dishwasher safe. Perfect as a gift or for home decoration.",
    category_id: "home_living_home_decor",
    condition: "NEW",
    image_urls_original: [
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
    ],
    serial_number: null,
    model_number: null,
    discount_schedule: "Turbo-30",
    zip_code: "77006",

    // Display fields
    seller_name: "ArtisanCraft",
    location: "Montrose / Museum District",
    rating: 4.9,
    reviews: 31,
    timeLeft: "4d 7h",
    isFavorite: false,
  },
];

export default function ListingsPage() {
  const [listings, setListings] = useState(mockListings);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [sortBy, setSortBy] = useState("relevance");
  const [showHidden, setShowHidden] = useState(false);
  const [showSaved, setShowSaved] = useState(false);
  const [savedListings, setSavedListings] = useState<Set<string>>(new Set());
  const [hiddenListings, setHiddenListings] = useState<Set<string>>(new Set());
  const [selectedListing, setSelectedListing] = useState<any>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  // Filter and sort listings
  const filteredListings = listings
    .filter((listing) => {
      const matchesSearch =
        listing.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        listing.category_id.toLowerCase().includes(searchTerm.toLowerCase()) ||
        listing.seller_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        listing.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
        listing.location.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesCategory =
        selectedCategory === "All" ||
        listing.category_id.includes(selectedCategory.toLowerCase());
      const isHidden = hiddenListings.has(listing.item_id);
      const isSaved = savedListings.has(listing.item_id);
      const shouldShowHidden = showHidden || !isHidden;
      const shouldShowSaved = !showSaved || isSaved;

      return (
        matchesSearch && matchesCategory && shouldShowHidden && shouldShowSaved
      );
    })
    .sort((a, b) => {
      switch (sortBy) {
        case "price-low":
          return a.list_price - b.list_price;
        case "price-high":
          return b.list_price - a.list_price;
        case "newest":
          return (
            new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
          );
        case "rating":
          return b.rating - a.rating;
        default:
          return 0;
      }
    });

  const toggleFavorite = (id: string) => {
    setListings(
      listings.map((listing) =>
        listing.item_id === id
          ? { ...listing, isFavorite: !listing.isFavorite }
          : listing
      )
    );
  };

  const toggleSaved = (id: string) => {
    setSavedListings((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  };

  const toggleHidden = (id: string) => {
    setHiddenListings((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  };

  const openModal = (listing: any) => {
    setSelectedListing(listing);
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
    setSelectedListing(null);
  };

  const categories = [
    "All",
    "Furniture",
    "Electronics",
    "Sports & Outdoors",
    "Home & Living",
    "Fashion",
  ];

  const getConditionColor = (condition: string) => {
    switch (condition) {
      case "NEW":
        return "bg-blue-100 text-blue-800";
      case "EXCELLENT":
        return "bg-green-100 text-green-800";
      case "GOOD":
        return "bg-yellow-100 text-yellow-800";
      case "FAIR":
        return "bg-orange-100 text-orange-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const getDiscountScheduleColor = (schedule: string) => {
    return schedule === "Turbo-30"
      ? "bg-red-100 text-red-800"
      : "bg-purple-100 text-purple-800";
  };

  const getZipCodeStatus = (zipCode: string) => {
    const isApproved = isApprovedBuyerZipCode(zipCode);
    const neighborhood = getNeighborhoodName(zipCode);
    return { isApproved, neighborhood };
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex flex-col sm:flex-row gap-4 items-center justify-between">
            <h1 className="text-2xl font-bold text-gray-900">
              Active Listings
            </h1>

            {/* Search Bar */}
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
              <input
                type="text"
                placeholder="Search listings..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D4AF3D] focus:border-transparent"
              />
            </div>

            {/* Filter Controls */}
            <div className="flex gap-2">
              <select
                value={selectedCategory}
                onChange={(e) => setSelectedCategory(e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D4AF3D] focus:border-transparent"
              >
                {categories.map((category) => (
                  <option key={category} value={category}>
                    {category}
                  </option>
                ))}
              </select>

              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D4AF3D] focus:border-transparent"
              >
                <option value="relevance">Relevance</option>
                <option value="price-low">Price: Low to High</option>
                <option value="price-high">Price: High to Low</option>
                <option value="newest">Newest First</option>
                <option value="rating">Highest Rated</option>
              </select>

              {/* Show Saved Toggle */}
              <Button
                variant={showSaved ? "default" : "outline"}
                size="sm"
                onClick={() => setShowSaved(!showSaved)}
                className="flex items-center gap-2"
              >
                <Bookmark className="h-4 w-4" />
                {showSaved ? "Show All" : "Saved Only"}
              </Button>

              {/* Show Hidden Toggle */}
              <Button
                variant={showHidden ? "default" : "outline"}
                size="sm"
                onClick={() => setShowHidden(!showHidden)}
                className="flex items-center gap-2"
              >
                <EyeOff className="h-4 w-4" />
                {showHidden ? "Hide Hidden" : "Show Hidden"}
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Results Count */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div className="flex items-center justify-between">
          <p className="text-gray-600">
            Showing {filteredListings.length} of {listings.length} listings
          </p>
          <div className="flex items-center gap-4 text-sm text-gray-600">
            <span className="flex items-center gap-1">
              <Bookmark className="h-4 w-4 text-[#D4AF3D]" />
              {savedListings.size} saved
            </span>
            <span className="flex items-center gap-1">
              <EyeOff className="h-4 w-4 text-gray-500" />
              {hiddenListings.size} hidden
            </span>
          </div>
        </div>
      </div>

      {/* Listings Grid */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-8">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {filteredListings.map((listing) => {
            const zipStatus = getZipCodeStatus(listing.zip_code);
            const isSaved = savedListings.has(listing.item_id);
            const isHidden = hiddenListings.has(listing.item_id);

            return (
              <div
                key={listing.item_id}
                className={`bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200 overflow-hidden ${
                  isHidden ? "opacity-60" : ""
                }`}
              >
                {/* Image Container */}
                <div className="relative aspect-square overflow-hidden">
                  <img
                    src={listing.image_urls_staged[0]}
                    alt={listing.title}
                    className="w-full h-full object-cover hover:scale-105 transition-transform duration-200"
                  />

                  {/* Favorite Button */}
                  <button
                    onClick={() => toggleFavorite(listing.item_id)}
                    className={`absolute top-2 right-2 p-2 rounded-full transition-colors ${
                      listing.isFavorite
                        ? "bg-red-500 text-white"
                        : "bg-white/80 text-gray-600 hover:bg-red-500 hover:text-white"
                    }`}
                  >
                    <Heart
                      className={`h-4 w-4 ${listing.isFavorite ? "fill-current" : ""}`}
                    />
                  </button>

                  {/* Time Left Badge */}
                  <div className="absolute bottom-2 left-2 bg-black/70 text-white px-2 py-1 rounded text-xs flex items-center gap-1">
                    <Clock className="h-3 w-3" />
                    {listing.timeLeft}
                  </div>

                  {/* Discount Schedule Badge */}
                  <div
                    className={`absolute top-2 left-2 px-2 py-1 rounded text-xs font-bold ${getDiscountScheduleColor(listing.discount_schedule)}`}
                  >
                    {listing.discount_schedule}
                  </div>

                  {/* QR Code Badge */}
                  <div className="absolute bottom-2 right-2 bg-white/90 p-1 rounded">
                    <QrCode className="h-4 w-4 text-gray-600" />
                  </div>

                  {/* Hidden Badge */}
                  {isHidden && (
                    <div className="absolute top-2 left-12 bg-gray-600 text-white px-2 py-1 rounded text-xs font-bold">
                      HIDDEN
                    </div>
                  )}
                </div>

                {/* Content */}
                <div className="p-4">
                  {/* Title */}
                  <h3 className="font-semibold text-gray-900 text-sm line-clamp-2 mb-2 hover:text-[#D4AF3D] cursor-pointer">
                    {listing.title}
                  </h3>

                  {/* Price Range & List Price */}
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-lg font-bold text-gray-900">
                      ${listing.list_price.toFixed(2)}
                    </span>
                    <span className="text-xs text-gray-500">
                      (${listing.price_range_low}-${listing.price_range_high})
                    </span>
                  </div>

                  {/* Rating */}
                  <div className="flex items-center gap-1 mb-2">
                    <Star className="h-3 w-3 fill-yellow-400 text-yellow-400" />
                    <span className="text-xs text-gray-600">
                      {listing.rating}
                    </span>
                    <span className="text-xs text-gray-400">
                      ({listing.reviews})
                    </span>
                  </div>

                  {/* Condition & Location */}
                  <div className="flex items-center justify-between text-xs text-gray-500 mb-3">
                    <span
                      className={`px-2 py-1 rounded ${getConditionColor(listing.condition)}`}
                    >
                      {listing.condition}
                    </span>
                    <div className="flex items-center gap-1">
                      <MapPin className="h-3 w-3" />
                      {listing.location}
                    </div>
                  </div>

                  {/* ZIP Code Status */}
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-xs font-medium text-gray-700">
                      ZIP: {listing.zip_code}
                    </span>
                    {zipStatus.isApproved ? (
                      <div className="flex items-center gap-1 text-xs text-green-600">
                        <CheckCircle className="h-3 w-3" />
                        <span>Approved Zone</span>
                      </div>
                    ) : (
                      <div className="flex items-center gap-1 text-xs text-red-600">
                        <AlertCircle className="h-3 w-3" />
                        <span>Outside Zone</span>
                      </div>
                    )}
                  </div>

                  {/* Seller */}
                  <div className="text-xs text-gray-600 mb-2">
                    by{" "}
                    <span className="text-[#D4AF3D] font-medium">
                      {listing.seller_name}
                    </span>
                  </div>

                  {/* Item ID & Fee */}
                  <div className="text-xs text-gray-400 mb-3 flex items-center justify-between">
                    <span className="flex items-center gap-1">
                      <Tag className="h-3 w-3" />
                      {listing.item_id.slice(-8)}
                    </span>
                    <span className="text-[#D4AF3D] font-medium">
                      {listing.fee_pct}% fee
                    </span>
                  </div>

                  {/* Serial/Model Numbers */}
                  {(listing.serial_number || listing.model_number) && (
                    <div className="text-xs text-gray-400 mb-3">
                      {listing.serial_number && (
                        <div>SN: {listing.serial_number}</div>
                      )}
                      {listing.model_number && (
                        <div>Model: {listing.model_number}</div>
                      )}
                    </div>
                  )}

                  {/* Action Buttons */}
                  <div className="flex gap-2">
                    <Button
                      variant="default"
                      className="flex-1 bg-[#D4AF3D] hover:bg-[#b8932f] text-white text-sm"
                      disabled={!zipStatus.isApproved}
                      onClick={() => openModal(listing)}
                    >
                      {zipStatus.isApproved
                        ? "View Details"
                        : "Zone Restricted"}
                    </Button>

                    {/* Save Button */}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => toggleSaved(listing.item_id)}
                      className={`px-3 transition-colors ${
                        isSaved
                          ? "bg-[#D4AF3D] text-white border-[#D4AF3D]"
                          : "hover:bg-[#D4AF3D] hover:text-white hover:border-[#D4AF3D]"
                      }`}
                    >
                      <Bookmark
                        className={`h-4 w-4 ${isSaved ? "fill-current" : ""}`}
                      />
                    </Button>

                    {/* Hide Button */}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => toggleHidden(listing.item_id)}
                      className={`px-3 transition-colors ${
                        isHidden
                          ? "bg-gray-600 text-white border-gray-600"
                          : "hover:bg-gray-600 hover:text-white hover:border-gray-600"
                      }`}
                    >
                      <EyeOff
                        className={`h-4 w-4 ${isHidden ? "fill-current" : ""}`}
                      />
                    </Button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* No Results */}
        {filteredListings.length === 0 && (
          <div className="text-center py-12">
            <div className="text-gray-400 mb-4">
              <Search className="h-12 w-12 mx-auto" />
            </div>
            <h3 className="text-lg font-medium text-gray-900 mb-2">
              No listings found
            </h3>
            <p className="text-gray-500">
              Try adjusting your search or filter criteria
            </p>
          </div>
        )}
      </div>

      {/* Listing Details Modal */}
      {isModalOpen && selectedListing && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg max-w-4xl w-full max-h-[90vh] overflow-y-auto">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-6 border-b border-gray-200">
              <h2 className="text-2xl font-bold text-gray-900">
                {selectedListing.title}
              </h2>
              <button
                onClick={closeModal}
                className="p-2 hover:bg-gray-100 rounded-full transition-colors"
              >
                <X className="h-6 w-6 text-gray-500" />
              </button>
            </div>

            {/* Modal Content */}
            <div className="p-6">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Left Column - Image and Basic Info */}
                <div>
                  {/* Main Image */}
                  <div className="mb-6">
                    <img
                      src={selectedListing.image_urls_staged[0]}
                      alt={selectedListing.title}
                      className="w-full h-96 object-cover rounded-lg"
                    />
                  </div>

                  {/* Price Information */}
                  <div className="bg-gray-50 p-4 rounded-lg mb-6">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-3xl font-bold text-gray-900">
                        ${selectedListing.list_price.toFixed(2)}
                      </span>
                      <span
                        className={`px-3 py-1 rounded-full text-sm font-medium ${getDiscountScheduleColor(selectedListing.discount_schedule)}`}
                      >
                        {selectedListing.discount_schedule}
                      </span>
                    </div>
                    <div className="text-sm text-gray-600">
                      Price Range: ${selectedListing.price_range_low} - $
                      {selectedListing.price_range_high}
                    </div>
                    {selectedListing.reserve_price && (
                      <div className="text-sm text-gray-600">
                        Reserve Price: $
                        {selectedListing.reserve_price.toFixed(2)}
                      </div>
                    )}
                    <div className="text-sm text-[#D4AF3D] font-medium mt-2">
                      ConsignCrew Fee: {selectedListing.fee_pct}%
                    </div>
                  </div>

                  {/* Action Buttons */}
                  <div className="flex gap-3 mb-6">
                    <Button
                      variant="default"
                      className="flex-1 bg-[#D4AF3D] hover:bg-[#b8932f] text-white"
                    >
                      Contact Seller
                    </Button>
                    <Button
                      variant="outline"
                      onClick={() => toggleSaved(selectedListing.item_id)}
                      className={`${
                        savedListings.has(selectedListing.item_id)
                          ? "bg-[#D4AF3D] text-white border-[#D4AF3D]"
                          : ""
                      }`}
                    >
                      <Bookmark
                        className={`h-4 w-4 mr-2 ${
                          savedListings.has(selectedListing.item_id)
                            ? "fill-current"
                            : ""
                        }`}
                      />
                      {savedListings.has(selectedListing.item_id)
                        ? "Saved"
                        : "Save"}
                    </Button>
                  </div>
                </div>

                {/* Right Column - Details */}
                <div>
                  {/* Item Details */}
                  <div className="mb-6">
                    <h3 className="text-lg font-semibold text-gray-900 mb-4">
                      Item Details
                    </h3>
                    <div className="space-y-3">
                      <div className="flex items-center gap-3">
                        <Package className="h-5 w-5 text-gray-400" />
                        <div>
                          <span className="text-sm font-medium text-gray-700">
                            Condition:
                          </span>
                          <span
                            className={`ml-2 px-2 py-1 rounded text-xs ${getConditionColor(selectedListing.condition)}`}
                          >
                            {selectedListing.condition}
                          </span>
                        </div>
                      </div>
                      <div className="flex items-center gap-3">
                        <Calendar className="h-5 w-5 text-gray-400" />
                        <div>
                          <span className="text-sm font-medium text-gray-700">
                            Listed:
                          </span>
                          <span className="ml-2 text-sm text-gray-600">
                            {formatDate(selectedListing.created_at)}
                          </span>
                        </div>
                      </div>
                      <div className="flex items-center gap-3">
                        <Clock className="h-5 w-5 text-gray-400" />
                        <div>
                          <span className="text-sm font-medium text-gray-700">
                            Time Left:
                          </span>
                          <span className="ml-2 text-sm text-gray-600">
                            {selectedListing.timeLeft}
                          </span>
                        </div>
                      </div>
                      {selectedListing.serial_number && (
                        <div className="flex items-center gap-3">
                          <Tag className="h-5 w-5 text-gray-400" />
                          <div>
                            <span className="text-sm font-medium text-gray-700">
                              Serial Number:
                            </span>
                            <span className="ml-2 text-sm text-gray-600">
                              {selectedListing.serial_number}
                            </span>
                          </div>
                        </div>
                      )}
                      {selectedListing.model_number && (
                        <div className="flex items-center gap-3">
                          <Tag className="h-5 w-5 text-gray-400" />
                          <div>
                            <span className="text-sm font-medium text-gray-700">
                              Model Number:
                            </span>
                            <span className="ml-2 text-sm text-gray-600">
                              {selectedListing.model_number}
                            </span>
                          </div>
                        </div>
                      )}
                      {selectedListing.gtin && (
                        <div className="flex items-center gap-3">
                          <Tag className="h-5 w-5 text-gray-400" />
                          <div>
                            <span className="text-sm font-medium text-gray-700">
                              GTIN:
                            </span>
                            <span className="ml-2 text-sm text-gray-600">
                              {selectedListing.gtin}
                            </span>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Seller Information */}
                  <div className="mb-6">
                    <h3 className="text-lg font-semibold text-gray-900 mb-4">
                      Seller Information
                    </h3>
                    <div className="bg-gray-50 p-4 rounded-lg">
                      <div className="flex items-center gap-3 mb-3">
                        <User className="h-5 w-5 text-gray-400" />
                        <div>
                          <span className="text-sm font-medium text-gray-700">
                            Seller:
                          </span>
                          <span className="ml-2 text-sm text-[#D4AF3D] font-medium">
                            {selectedListing.seller_name}
                          </span>
                        </div>
                      </div>
                      <div className="flex items-center gap-3 mb-3">
                        <MapPin className="h-5 w-5 text-gray-400" />
                        <div>
                          <span className="text-sm font-medium text-gray-700">
                            Location:
                          </span>
                          <span className="ml-2 text-sm text-gray-600">
                            {selectedListing.location}
                          </span>
                        </div>
                      </div>
                      <div className="flex items-center gap-3">
                        <Star className="h-5 w-5 text-yellow-400" />
                        <div>
                          <span className="text-sm font-medium text-gray-700">
                            Rating:
                          </span>
                          <span className="ml-2 text-sm text-gray-600">
                            {selectedListing.rating} ({selectedListing.reviews}{" "}
                            reviews)
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Description */}
                  <div className="mb-6">
                    <h3 className="text-lg font-semibold text-gray-900 mb-4">
                      Description
                    </h3>
                    <p className="text-gray-700 leading-relaxed">
                      {selectedListing.description}
                    </p>
                  </div>

                  {/* Item ID */}
                  <div className="text-xs text-gray-400">
                    Item ID: {selectedListing.item_id}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
